name: portfolio
description: A new Flutter project.

publish_to: "none"
version: 0.0.1+2

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.13.0
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0
  styled_text: ^8.1.0
  firebase_core: ^2.4.0
  firebase_app_check: ^0.2.1+18
  cloud_firestore: ^4.3.0
  basic_utils: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
